In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("delivery_time.csv")
df = data.copy()

In [5]:
df

    Delivery Time  Sorting Time
0           21.00            10
1           13.50             4
2           19.75             6
3           24.00             9
4           29.00            10
5           15.35             6
6           19.00             7
7            9.50             3
8           17.90            10
9           18.75             9
10          19.83             8
11          10.75             4
12          16.68             7
13          11.50             3
14          12.03             3
15          14.88             4
16          13.75             6
17          18.11             7
18           8.00             2
19          17.83             7
20          21.50             5

In [11]:
y = df.iloc[:,0:1]

In [9]:
x = df.iloc[:,1:]
x

    Sorting Time
0             10
1              4
2              6
3              9
4             10
5              6
6              7
7              3
8             10
9              9
10             8
11             4
12             7
13             3
14             3
15             4
16             6
17             7
18             2
19             7
20             5

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X=x_train, y=y_train)

LinearRegression()

In [16]:
y_pred = linreg.predict(x_test)

In [18]:
comp = pd.DataFrame({"predicted":np.array(y_pred).reshape(-1),"actual":np.array(y_test).reshape(-1)})
comp

   predicted  actual
0  24.924743   21.00
1  18.852010   18.11
2  12.779276   14.88
3  12.779276   13.50
4  24.924743   17.90

In [20]:
from sklearn.metrics import r2_score
r2_score(y_true=y_test,y_pred=y_pred)

-1.020759958636741